sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: yilena_take_out
    username: root
    password: XUWENBO219382

  aliyun:
    oss:
      endpoint: https://oss-cn-beijing.aliyuncs.com
      bucketName: yilena-practice-project
      region: cn-beijing

  redis:
    host: localhost
    port: 6379
    database: 0